[code]
editor = 'nvim'
lang = 'java'
comment_leading = "//"
edit_code_marker = true
comment_problem_desc = true 
start_marker = "start_marker"
end_marker = "end_marker"
test = true

[cookies]
csrf = '9RytYYv88gEt2lSE7N4cflOxKcL8IBaQQehypJ5R4IObUiLCBByxbXGP2aIfQ9L2'
session = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfYXV0aF91c2VyX2lkIjoiNDkzNDMxMCIsIl9hdXRoX3VzZXJfYmFja2VuZCI6ImFsbGF1dGguYWNjb3VudC5hdXRoX2JhY2tlbmRzLkF1dGhlbnRpY2F0aW9uQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6IjBhNjVmZDdlMDliM2U0MzAxNGYyOTFlYzdjYjQ0ODRlNWM2NzI4MTMiLCJpZCI6NDkzNDMxMCwiZW1haWwiOiJrdWhlcmFtNzc3QGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiaGVtcmFtIiwidXNlcl9zbHVnIjoiaGVtcmFtIiwiYXZhdGFyIjoiaHR0cHM6Ly9hc3NldHMubGVldGNvZGUuY29tL3VzZXJzL2hlbXJhbS9hdmF0YXJfMTYzMjAzMjM5MC5wbmciLCJyZWZyZXNoZWRfYXQiOjE2OTQ1Mzk2MjEsImlwIjoiNDUuMTI0LjE0Ni4zOSIsImlkZW50aXR5IjoiMzM1N2ZhZGIwMzE2OTM5MzUyYmJkZDRkNTM2MGE5N2YiLCJzZXNzaW9uX2lkIjo0NjEzNDM0NX0._fkVVkhM_VAye2RZ6p1ygrlnAM0kDb_VnpoX5IyK8g8'

[storage]
cache = 'Problems'
code = 'striver'
root = '~/.leetcode/leetcode'

