#!/usr/bin/env bash

hydrate() {
    local session_name="$1"
    local session_type="$2"
    local sessions_file="/home/hemram/.config/sessions.json"

    [[ -f "$sessions_file" ]] || return 1

    local windows_json
    windows_json=$(jq -c ".\"${session_type}\"[\"${session_name}\"] // empty" "$sessions_file")
    [[ -n "$windows_json" ]] || return 0

    win_exists() {
        tmux list-windows -t "$session_name" -F '#{window_name}' 2>/dev/null | grep -Fxq "$1"
    }

    echo "$windows_json" | jq -c '.[]' | while read -r win; do
        local window_name cmd
        window_name=$(jq -r '.name' <<<"$win")
        cmd=$(jq -r '.cmd' <<<"$win")

        # Create window if missing
        if ! win_exists "$window_name"; then
            tmux new-window -t "$session_name" -n "$window_name" -c "$session"
        fi

        # Send the command
        tmux send-keys -t "${session_name}:${window_name}" "$cmd" C-m
    done
    tmux select-window -t "$session_name:0"
}

tmux_has_exact_session() {
	local search_name="$1"

	# Get all session names and compare exactly
	tmux list-sessions -F "#{session_name}" | grep -Fx "$search_name" >/dev/null 2>&1

	return $?
}

session=$(fdfind --hidden --type d --min-depth 0 --max-depth 1 . ~/.config | fzf --header 'Select Configuration Directory' --border-label 'Config Session')

if [ -z "$session" ]; then
	exit 1
fi

session_name="_config_$(basename $session)"

if [[ -z $TMUX ]]; then
	tmux new-session -s "$session_name" -c "$session" -d
	hydrate "$session_name" "config_sessions"
	tmux attach -t "$session_name"
	exit 0
fi

if ! tmux_has_exact_session "$session_name"; then
	tmux new-session -s "$session_name" -c "$session" -d
	hydrate "$session_name" "config_sessions"
fi

tmux switch-client -t "$session_name"
