#!/usr/bin/env bash

session_name="leet"
directory="/home/hemram/leet"

# Check if the tmux session exists
if ! tmux has-session -t "$session_name" 2> /dev/null; then
    tmux new-session -s "$session_name" -c "$directory" -d
fi

# Switch to the tmux session
tmux switch-client -t "$session_name"

# Execute the ls command after switching to the session
tmux send-keys -t "$session_name" 'nvim leetcode.nvim' C-m

