#!/usr/bin/env bash
 

die() {
    printf "\33[2K\r\033[1;31m%s\033[0m\n" "$*" >&2
    exit 1
}


launcher() {
    [ -z "$1" ] && set -- "+m" "$2"
    fzf "$1" --reverse --cycle --prompt "$2"
}

nth() {
    stdin=$(cat -)
    [ -z "$stdin" ] && return 1
    line_count="$(printf "%s\n" "$stdin" | wc -l | tr -d "[:space:]")"
    [ "$line_count" -eq 1 ] && printf "%s" "$stdin" | cut -f2,3 && return 0
    prompt="$1"
    multi_flag=""
    [ $# -ne 1 ] && shift && multi_flag="$1"
    line=$(printf "%s" "$stdin" | cut -f1,3 | tr '\t' ' ' | launcher "$multi_flag" "$prompt" | cut -d " " -f 1)
    [ -n "$line" ] && printf "%s" "$stdin" | grep -E '^'"${line}"'($|[[:space:]])' | cut -f2,3 
}

search_movie(){
result=$(curl -s "https://backend.freek.to/api/search?type=movie&page=1&query=$1&_=20241008" \
  -H 'origin: https://freek.to' \
  -H 'referer: https://freek.to/' \
  --data-raw '{"filters":[{"value":"any","key":"with_genres","isChanged":false},{"value":"any","key":"year","isChanged":false},{"value":"popularity.desc","key":"sort_by","isChanged":false},{"value":"any","key":"with_origin_country","isChanged":false}]}')

echo $result | jq -r '.results[] | [.id, .title] | @tsv'
}

help_info() {
    printf "\033[1;36m%s\033[0m\n" "Usage: movie [OPTIONS] [ARGS]"
    printf "\n"
    printf "\033[1;36m%s\033[0m\n" "Options:"
    printf "\n"
    printf "  \033[1;36m%s\033[0m\n" "-h, --help"
    printf "    Show help message and exit.\n"
    printf "\n"
    printf "\033[1;36m%s\033[0m\n" "Arguments:"
    printf "\n"
    printf "  \033[1;36m%s\033[0m\n" "[ARGS]"
    printf "    Search query.\n"
    printf "\n"
    exit 0
}

while [ $# -gt 0 ]; do
    case "$1" in
        -h | --help) help_info ;;
        *) query="$(printf "%s" "$query $1" | sed "s|^ ||;s| |+|g")" ;;
    esac
    shift
done

while [ -z "$query" ]; do
    printf "\33[2K\r\033[1;36mSearch anime: \033[0m" && read -r query
done

query=$(printf "%s" "$query" | sed "s| |%20|g")
movie_list=$(search_movie "$query")
[ -z "$movie_list" ] && die "No results found!"
printf "%s\n" "$movie_list"



