#!/usr/bin/env bash

item=$1
item_basename=$(basename "$item" .cpp)

compiler_cpp(){
    clang++ -static -s -lm -DLOCAL -Wall -O2 -std=c++17 -o "$item_basename" "$item"

    if [[ $? -ne 0 ]]; then 
        echo "Compilation failed"
        exit 1
    fi
}

# running codeforces tests
cp_runner_cpp(){

    compiler_cpp

    for input_file in "${item_basename}"*[0-9].in; do

        if [[ ! -f "$input_file" ]]; then
            normal_runner_cpp
            exit 1
        fi

        test_case_num=$(echo "$input_file" | grep -o '[0-9]*')
        answer_file="${item_basename}${test_case_num}.ans"

        program_output=$(./"$item_basename" < "$input_file")
        exit_status=$?

        if [[ $exit_status -eq 0 ]]; then
            if [[ -f "$answer_file" ]]; then

                if diff -q <(echo "$program_output") "$answer_file" > /dev/null; then
                    echo "===== Test case $test_case_num passed. ====="
                else
                    echo "===== Test case $test_case_num failed. ====="
                    diff -y <(echo "$program_output") "$answer_file"
                fi
            else
                echo "Answer file $answer_file does not exist."
            fi
        else
            echo "Program failed to run for test case $test_case_num."
        fi
    done
}

normal_runner_cpp(){
    if [[ ! -f "$item_basename.in" ]]; then
        touch "$item_basename.in"
    fi

    timeout 2s ./"$item_basename" < "$item_basename.in"
}

case "$item" in
    *.cpp)
        cp_runner_cpp "$item"
        ;;
    *)
        echo "Invalid file type"
        exit 1
        ;;
esac
