#!/usr/bin/env bash

hydrate() {
    local session_name="$1"
    local session_type="$2"
    local sessions_file="$HOME/.config/sessions.json"

    [[ -f "$sessions_file" ]] || return 1

    local windows_json
    windows_json=$(jq -c ".\"${session_type}\"[\"${session_name}\"] // empty" "$sessions_file")
    [[ -n "$windows_json" ]] || return 0

    win_exists() {
        tmux list-windows -t "$session_name" -F '#{window_name}' 2>/dev/null | grep -Fxq "$1"
    }

    echo "$windows_json" | jq -c '.[]' | while read -r win; do
        local window_name cmd
        window_name=$(jq -r '.name' <<<"$win")
        cmd=$(jq -r '.cmd' <<<"$win")

        # Create window if missing
        if ! win_exists "$window_name"; then
            tmux new-window -t "$session_name" -n "$window_name" -c "$session"
        fi

        # Send the command
        tmux send-keys -t "${session_name}:${window_name}" "$cmd" C-m
    done
    tmux select-window -t "$session_name:0"
}


tmux_has_exact_session() {
    local search_name="$1"

    # Get all session names and compare exactly
    tmux list-sessions -F "#{session_name}" | grep -Fx "$search_name" >/dev/null 2>&1

    return $?
}

find_dirs() {

    if [[ -n "${TMUX}" ]]; then
        current_session=$(tmux display-message -p '#S')
        tmux list-sessions -F "[TMUX] #{session_name}" 2>/dev/null | grep -vFx "[TMUX] $current_session"
    else
        tmux list-sessions -F "[TMUX] #{session_name}" 2>/dev/null
    fi

    fdfind --hidden --type d \
        --exclude .git --exclude .logs --exclude .vscode --exclude .github \
        --min-depth 0 --max-depth 1 . \
        /home ~ ~/test ~/.local ~/.local/bin ~/.local/share/nvim/lazy ~/learn ~/git-repos ~/git-repos/dumpyard \
        ~/git-repos/dumpyard/DesignPatterns/src
}

if [[ $# -eq 1 ]]; then
    session=$1
else
    session=$(
        find_dirs |
            fzf --header 'Select Session you need' --border-label 'Sessionizer'
    )
fi

if [[ -z $session ]]; then
    exit 1
fi

if [[ "$session" =~ ^\[TMUX\]\ (.+)$ ]]; then
    session="${BASH_REMATCH[1]}"
fi

session_name=$(basename "$session" | tr . _)

if [[ -z $TMUX ]]; then
    tmux new-session -s "$session_name" -c "$session" -d
    hydrate "$session_name" "sessions"
    tmux attach -t "$session_name"
    exit 0
fi

if ! tmux_has_exact_session "$session_name"; then
    tmux new-session -s "$session_name" -c "$session" -d
    hydrate "$session_name" "sessions"
fi

tmux switch-client -t "$session_name"
