#!/usr/bin/env bash

session=$( fdfind --hidden \
                  --type d \
                  --exclude .git --exclude .logs --exclude .vscode --exclude .github \
                  --min-depth 0 --max-depth 1 . \
        /home ~ ~/work ~/web3 ~/.local ~/.local/bin ~/junkyard ~/git-repos ~/git-repos/dumpyard/DesignPatterns/src ~/git-repos/dumpyard/ProblemSolving ~/git-repos/dumpyard/ProblemSolving/cf/contests \
        | fzf --header 'Select Session you need' --border-label 'Sessionizer' )

session_name=$(basename "$session" | tr . _)

if ! tmux has-session -t "$session_name" 2> /dev/null; then
    tmux new-session -s "$session_name" -c "$session" -d
fi

tmux switch-client -t "$session_name"

       
