#!/usr/bin/env bash

read -p "Search :" query

command=$(rg --line-number $query | fzf)

filename=$(echo $command | awk -F ':' '{print $1}')
linenumber=$(echo $command | awk -F ':' '{print $2}')

nvim +$linenumber $filename

